stages:
  - build
  - test

matrix:
  include:
    - stage: build
      language: python
      os: linux
      python: 3.6
      env:
        - BUILDMODE=sdist
        - ARTIFACT_PATH=sdist

    - stage: build
      language: generic
      os: linux
      env:
        - BUILDMODE=manylinuxwheels
        - ARTIFACT_PATH=manylinuxwheels
      sudo: required
      services:
        - docker

    - stage: build
      language: generic
      os: osx
      env:
        - BUILDMODE=macoswheels
        - ARTIFACT_PATH=macos

    - stage: build
      language: python
      os: linux
      python: 2.7
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/2.7

    - stage: build
      language: python
      os: linux
      python: 3.4
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/3.4

    - stage: build
      language: python
      os: linux
      python: 3.5
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/3.5

    - stage: build
      language: python
      os: linux
      python: 3.6
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/3.6

    - stage: build
      language: python
      os: linux
      python: 3.6-dev
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/3.6-dev

    - stage: build
      language: python
      os: linux
      python: 3.7-dev
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/3.7-dev

    - stage: build
      language: python
      os: linux
      python: nightly
      env:
        - BUILDMODE=tox
        - ARTIFACT_PATH=tox/nightly

    - stage: build
      language: python
      os: linux
      python: 2.7
      env:
        - BUILDMODE=conda
        - ARTIFACT_PATH=conda/2.7

    - stage: build
      language: python
      os: linux
      python: 3.5
      env:
        - BUILDMODE=conda
        - ARTIFACT_PATH=conda/3.5

    - stage: build
      language: python
      os: linux
      python: 3.6
      env:
        - BUILDMODE=conda
        - ARTIFACT_PATH=conda/3.6

    - stage: test
      language: python
      os: linux
      python: 2.7
      env:
        - BUILDMODE=manylinuxtest

    - stage: test
      language: python
      os: linux
      python: 3.4
      env:
        - BUILDMODE=manylinuxtest

    - stage: test
      language: python
      os: linux
      python: 3.5
      env:
        - BUILDMODE=manylinuxtest

    - stage: test
      language: python
      os: linux
      python: 3.6
      env:
        - BUILDMODE=manylinuxtest

env:
  global:
    # Enable fuzzing tests, other expensive tests.
    - ZSTD_SLOW_TESTS=1
    - ZSTD_WARNINGS_AS_ERRORS=1

    # This tells Hypothesis to work harder than it does by default.
    - HYPOTHESIS_PROFILE=ci

    - ARTIFACTS_BUCKET=python-zstandard
    - ARTIFACTS_PERMISSIONS=public-read

    # ARTIFACTS_KEY
    - secure: nB7QXvYTQ+60WW8sh+JQSmBGI9EvXEigbhpmyjqCM5MZhnIQlWDXU/Ts2GbBZ75vTfYvOsDeVnOgL4yNbw3QiGAfntXHXSRLVPVWMg8hNLSO2FgQh/Ytw5XkYbVGnQve8giK5ZWgO877qMGepYrvtpIjIZbZ0fLfyVCMIKTJzYqewnH5EMzvsMxbxWe2Ojxd47DSmQkPlk6qHXupZ1t2FrCxcioXnWvwwVOAZWTvqMmgOtT3S/xRbZ1+US69LFebHcsusIOL7VzYunaTAgtOJUrS/QbW0ddbctM4qHSYIpwe/iQiGsWNsyJrViGAWg0r3SJr24bqjAzRSvNEwDvs9FhbQVcdZOKrH1KB/h34FkyQFQl+GuG7D4gZY8Eth8zW8p+Cz+SJHoiXjsCGdsmm+bPlKoZC4tJTzUtUmbpDt22BEbKqRObWIYQWLDQ6Keh7B4/tuGvl1r3cvsf/p66V8jwtpYP8papinjKYEwWCvPWBungpRcZ54ohPEmGOBer/nVTteZ9Q4rHBOlNu6Q1s2MooRHo+2K3u3aa43tFVgEi5XViC56g+KfQgB9Q2w6E8Vvj/enmDHKAhWlyFp7aliOXqzJBfFZluKwaccRsr/yaskNlSXdnRZS8/+m/oA7CnubpCh+fRPk6jf4g/l8fqw5spxx2f0lHEzfG243Vo4Q8=
    # ARTIFACTS_SECRET
    - secure: swX8M1dhvPirn69pSNzbmfuVi6asetIq49amJyGsIX0HyRHeUxS+ZOZrWTPXQhKWJJvKe+utToe7FFZH8xl7g8GtcQS0ufM41ScXCIMXDKsqtaBR2ISqKpHt7uHuO5J10DdDvdVekjUQRYkGDq6yIPheOudMgIAZzlTOVUUTfk/NWmmClW0VOI8yeusxNpVE2mNUXQ3ZElticVaHmmPrxqh9e3MXrhA7oe6j+IGtO18Cer5K97hQMRA8O5Sc6WAkYjcP757gZYWYiTLkC2Ifnud4PVJkkqH7vekDr97GnxFrt4u5ysZW3Aw124CYuc5fFtjWJsg/tV2/2qvwnqAtPVC0RGl98ztpEEldL2fyVc3EfQ47n4qvBnPNF2zo+To3eTIzEEZiPBrlrxhpq1GxVgo9ui8VsawPGEPtKu+qQ17JqIry5r4Wmk88mnIMblMxPGJ9+IQHvfJRMxNhREQXW8bBKHcIqJe1qZqidLdGGm7KhUUlIPRP28gqVL7U7s6RM2bGjBnRah8xixrM28K49Wrh5Ys+zYaqEI+zf6vQFapwgRAacoFvDrIjiTBzu8thJYhmhKbraTCkA8Ramaq0vhZK625ORjG9L8HR8jH05nqeGHgFi4H/VuR4nTRiRgO9ar9Ersp74zKh5rZqG7o0J/OSRHbqnABfLBzBGMP60wc=

install:
  - source ci/travis-install.sh

script:
  - source ci/travis-build.sh

addons:
  artifacts:
    s3_region: "us-west-2"
    target_paths: "/travis/${TRAVIS_BUILD_NUMBER}/${ARTIFACT_PATH}"
    paths:
      - $(ls dist/* | tr "\n" ":")
