[package]
name = "python-zstandard"
version = "0.15.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Python bindings to zstandard compression library"
readme = "README.rst"

[lib]
name = "zstandard_oxidized"
crate-type = ["cdylib"]
path = "rust-ext/src/lib.rs"

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
