[package]
name = "python-zstandard"
version = "0.15.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Python bindings to zstandard compression library"
readme = "README.rst"

[lib]
name = "zstandard_oxidized"
crate-type = ["cdylib"]
path = "rust-ext/src/lib.rs"

[dependencies]
libc = "0.2"
num_cpus = "1"
python3-sys = "0.5"

[dependencies.zstd-safe]
#version = "2.0.4"
git = "https://github.com/gyscos/zstd-rs.git"
rev = "65369fc477346223fe7ec2fecfdcb7e22e6ce0a9"
features = ["experimental", "legacy", "zstdmt"]

[dependencies.zstd-sys]
#version = "1.4.16"
git = "https://github.com/gyscos/zstd-rs.git"
rev = "65369fc477346223fe7ec2fecfdcb7e22e6ce0a9"
features = ["experimental", "legacy", "zstdmt"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
