jobs:
- job: Source_Distribution
  pool:
    vmImage: ubuntu-18.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.7
  - script: |
        python setup.py sdist
    displayName: Build
  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/dist

- template: azure-pipelines-anaconda-linux-template.yml
  parameters:
    name: Linux_Anaconda
    vmImage: ubuntu-18.04

- template: azure-pipelines-anaconda-windows-template.yml
  parameters:
    name: Windows_Anaconda
    vmImage: vs2017-win2016
