jobs:
- template: azure-pipelines-anaconda-linux-template.yml
  parameters:
    name: Linux_Anaconda
    vmImage: ubuntu-18.04

- template: azure-pipelines-anaconda-windows-template.yml
  parameters:
    name: Windows_Anaconda
    vmImage: vs2017-win2016
